/**
 * Central re-export of Lucide icons used across the SPA. Importing from
 * here lets us track our icon budget in a single place.
 *
 * Note: deep imports (`lucide-react/dist/esm/icons/<name>`) were evaluated
 * as a tree-shaking optimisation but rejected — lucide-react@0.400.0 ships
 * `"sideEffects": false`, so Vite already prunes unused icons from the
 * barrel (verified: identical bundle size both ways). Deep paths also lack
 * .d.ts declarations and would require disabling type-checking.
 */
export {
  Plus,
  Settings,
  FolderOpen,
  FolderPlus,
  FolderSearch,
  FolderClosed,
  Folder,
  RefreshCw,
  File,
  FileText,
  FileCode,
  FileJson,
  FileImage,
  FileArchive,
  Image as ImageIcon,
  Archive,
  Search,
  MoreHorizontal,
  ArrowUp,
  ArrowDown,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  Send,
  Square,
  Check,
  X,
  AlertTriangle,
  Loader2,
  Paperclip,
  Mic,
  MicOff,
  Trash2,
  Copy,
  Cloud,
  Cpu,
  Edit,
  Terminal,
  MessageSquare,
  PanelLeftClose,
  PanelLeft,
  Slash,
  Command,
  BookOpen,
  Sparkles,
  Puzzle,
  Layers,
  Wrench,
  ToggleLeft,
  ToggleRight,
  Sun,
  Moon,
  Clock,
  Globe,
  Server,
  Eye,
  EyeOff,
  MoreVertical,
  SlidersHorizontal,
  Filter,
  Users,
  Network,
  GitBranch,
  Workflow,
  Crown,
  UserCog,
  ExternalLink,
  Info,
  Minus,
  GitFork,
  ShieldCheck,
  Languages,
  BarChart3,
  DollarSign,
  Bell,
  AlertCircle,
  CheckCircle2,
  Zap,
  Play,
  Pause,
  Volume2,
  VolumeX,
  StopCircle,
  Pencil,
  Eraser,
  Undo2,
  Redo2,
} from 'lucide-react';
