/**
 * /arch — inspect and manage `.localcode/arch.toml` layering rules.
 *
 * Subcommands:
 *   /arch                  alias for `/arch check`.
 *   /arch check            sweep the project, return violation count
 *                          plus the first 20 details.
 *   /arch rules            list the declared rules (id, match, forbid).
 *   /arch init             scaffold a starter arch.toml derived from
 *                          the current src/ layout (heuristic, no model
 *                          call).
 *   /arch ignore <regex>   append `<regex>` to `[global].ignoreImports`.
 *
 * Heuristic for `/arch init`: scan top-level subdirectories of `src/`,
 * emit one rule per discovered subdirectory whose body is `match =
 * 'src/<dir>/**'` with an empty `forbid` placeholder so the user has a
 * starter scaffold. We intentionally do NOT auto-detect actual layering
 * violations — that's the user's editorial call. The scaffold has clear
 * TODO comments inviting the user to fill in `forbid` lists.
 *
 * No LLM round-trip — every subcommand is a local filesystem operation.
 */

import { readdirSync, existsSync, writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import type { SlashCommand, CommandContext } from '@/types/global';
import {
  archConfigPath,
  loadArchConfig,
  validateProject,
  type ArchConfig,
} from '@/architecture';

const NAME = 'arch';
const DESCRIPTION =
  'Architecture rules — check, list, init, or ignore imports.';
const USAGE = '/arch [check|rules|init|ignore <regex>]';

/** Maximum violation entries to print per `/arch check` invocation. */
const MAX_DETAIL_ROWS = 20;

export function createArchCommand(): SlashCommand {
  return {
    name: NAME,
    description: DESCRIPTION,
    usage: USAGE,
    execute: async (args: string, ctx: CommandContext): Promise<void> => {
      const trimmed = args.trim();
      const [sub, ...restParts] = trimmed.length > 0 ? trimmed.split(/\s+/) : ['check'];
      const restArg = restParts.join(' ');
      switch ((sub ?? 'check').toLowerCase()) {
        case 'check':
          await runCheck(ctx);
          return;
        case 'rules':
          runRules(ctx);
          return;
        case 'init':
          runInit(ctx);
          return;
        case 'ignore':
          runIgnore(ctx, restArg);
          return;
        default:
          ctx.print(`Unknown /arch subcommand: ${sub}. Usage: ${USAGE}`);
          return;
      }
    },
  };
}

async function runCheck(ctx: CommandContext): Promise<void> {
  const config = readConfig(ctx);
  if (config === null) return;
  ctx.print('Sweeping project for architecture violations...');
  let result;
  try {
    result = await validateProject(config, ctx.projectRoot);
  } catch (cause) {
    ctx.print(`/arch check failed: ${errMsg(cause)}`);
    return;
  }
  const { violations, filesChecked } = result;
  if (violations.length === 0) {
    ctx.print(`✓ No architecture violations across ${filesChecked} matched files.`);
    return;
  }
  ctx.print(
    `Found ${violations.length} violation${violations.length === 1 ? '' : 's'} across ${filesChecked} files. Showing first ${Math.min(violations.length, MAX_DETAIL_ROWS)}:`,
  );
  for (const v of violations.slice(0, MAX_DETAIL_ROWS)) {
    const target = v.resolvedTarget !== null ? ` → ${v.resolvedTarget}` : '';
    ctx.print(`  [${v.ruleId}] ${v.sourceFile}:${v.line} imports ${v.importPath}${target}`);
  }
  if (violations.length > MAX_DETAIL_ROWS) {
    ctx.print(`  ... ${violations.length - MAX_DETAIL_ROWS} more violations omitted`);
  }
}

function runRules(ctx: CommandContext): void {
  const config = readConfig(ctx);
  if (config === null) return;
  if (config.rule.length === 0) {
    ctx.print('No rules declared in arch.toml.');
    return;
  }
  ctx.print(`Active arch rules (${config.rule.length}):`);
  for (const rule of config.rule) {
    const desc = rule.description !== undefined ? ` — ${rule.description}` : '';
    ctx.print(`  ${rule.id}: match=${rule.match}${desc}`);
    if (rule.allowAll === true) {
      ctx.print('    allowAll: true');
    } else {
      for (const f of rule.forbid ?? []) {
        ctx.print(`    forbid: ${f}`);
      }
    }
  }
  if (config.global.ignoreImports.length > 0) {
    ctx.print('Global ignoreImports:');
    for (const pattern of config.global.ignoreImports) {
      ctx.print(`  ${pattern}`);
    }
  }
}

function runInit(ctx: CommandContext): void {
  const archPath = archConfigPath(ctx.projectRoot);
  if (existsSync(archPath)) {
    ctx.print(`arch.toml already exists at ${archPath} — refusing to overwrite. Edit by hand.`);
    return;
  }
  const lines: string[] = [];
  lines.push('# Architecture rules — edit to declare layering invariants.');
  lines.push('# Generated by /arch init. Adjust `forbid` lists below.');
  lines.push('');
  const srcRoot = path.join(ctx.projectRoot, 'src');
  const subdirs = listSrcSubdirs(srcRoot);
  if (subdirs.length === 0) {
    lines.push('# No `src/` subdirectories detected — declaring a single permissive rule.');
    lines.push('# TODO: replace `allowAll` with a `forbid = [...]` list to enforce layering.');
    lines.push('[[rule]]');
    lines.push('id = "default"');
    lines.push('description = "Adjust to declare your real layering"');
    lines.push('match = "src/**/*.{ts,tsx}"');
    lines.push('allowAll = true');
    lines.push('');
  } else {
    for (const dir of subdirs) {
      lines.push('[[rule]]');
      lines.push(`id = "${dir}-isolation"`);
      lines.push(`description = "Layer constraints for src/${dir}"`);
      lines.push(`match = "src/${dir}/**/*.{ts,tsx}"`);
      lines.push('# TODO: replace `allowAll` with a forbid list, e.g.');
      lines.push('#   forbid = ["src/llm/**", "src/web/**"]');
      lines.push('allowAll = true');
      lines.push('');
    }
  }
  lines.push('[[rule]]');
  lines.push('id = "tests-anywhere"');
  lines.push('match = "tests/**/*.ts"');
  lines.push('allowAll = true');
  lines.push('');
  lines.push('[global]');
  lines.push('ignoreImports = ["^bun:.*", "^node:.*", "^@/types/.*"]');
  lines.push('');
  try {
    mkdirSync(path.dirname(archPath), { recursive: true });
    writeFileSync(archPath, lines.join('\n'), 'utf8');
  } catch (cause) {
    ctx.print(`/arch init failed: ${errMsg(cause)}`);
    return;
  }
  ctx.print(`✓ Wrote starter rules to ${archPath}`);
  ctx.print(`  Detected ${subdirs.length} src/ subdirectories — review and fill in 'forbid' lists.`);
}

function runIgnore(ctx: CommandContext, pattern: string): void {
  const cleaned = pattern.trim();
  if (cleaned.length === 0) {
    ctx.print('Usage: /arch ignore <regex>');
    return;
  }
  // Validate it's a legal regex BEFORE persisting.
  try {
    new RegExp(cleaned);
  } catch (cause) {
    ctx.print(`Invalid regex: ${errMsg(cause)}`);
    return;
  }
  const archPath = archConfigPath(ctx.projectRoot);
  let raw = '';
  if (existsSync(archPath)) {
    try {
      raw = readFileSync(archPath, 'utf8');
    } catch (cause) {
      ctx.print(`Failed to read arch.toml: ${errMsg(cause)}`);
      return;
    }
  }
  const updated = appendIgnorePattern(raw, cleaned);
  try {
    mkdirSync(path.dirname(archPath), { recursive: true });
    writeFileSync(archPath, updated, 'utf8');
  } catch (cause) {
    ctx.print(`Failed to write arch.toml: ${errMsg(cause)}`);
    return;
  }
  ctx.print(`✓ Added ignoreImports pattern: ${cleaned}`);
}

// ---------- helpers ----------

function readConfig(ctx: CommandContext): ArchConfig | null {
  try {
    const config = loadArchConfig(ctx.projectRoot);
    if (config === null) {
      ctx.print(
        `No arch.toml at ${archConfigPath(ctx.projectRoot)}. Run /arch init to scaffold one.`,
      );
      return null;
    }
    return config;
  } catch (cause) {
    ctx.print(`Failed to load arch.toml: ${errMsg(cause)}`);
    return null;
  }
}

function listSrcSubdirs(srcRoot: string): string[] {
  if (!existsSync(srcRoot)) return [];
  try {
    const entries = readdirSync(srcRoot, { withFileTypes: true });
    return entries
      .filter((e) => e.isDirectory() && !e.name.startsWith('.') && e.name !== 'node_modules')
      .map((e) => e.name)
      .sort();
  } catch {
    return [];
  }
}

/**
 * Append `pattern` to the `[global].ignoreImports` list in raw TOML
 * text. Idempotent (skips when the exact pattern is already present)
 * and tolerant of a missing `[global]` block — falls back to appending
 * a fresh section. Kept as a string edit so unknown TOML structure
 * round-trips untouched.
 */
export function appendIgnorePattern(raw: string, pattern: string): string {
  // Quick-and-dirty dedupe — substring search inside the patterns line.
  const escapedPattern = pattern.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const dupCheck = new RegExp(`"${escapedPattern}"`);
  if (dupCheck.test(raw)) {
    return raw;
  }
  // Look for an existing `[global]` block with an ignoreImports = [ ... ] line.
  const ignoreLineRegex = /(^|\n)ignoreImports\s*=\s*\[([\s\S]*?)\]/;
  const match = raw.match(ignoreLineRegex);
  if (match !== null) {
    const inside = (match[2] ?? '').trim();
    const augmented = inside.length === 0 ? `"${pattern}"` : `${inside}, "${pattern}"`;
    return raw.replace(ignoreLineRegex, `$1ignoreImports = [${augmented}]`);
  }
  // No ignoreImports — check if a [global] block exists already.
  const globalRegex = /(^|\n)\[global\][^\n]*\n/;
  if (globalRegex.test(raw)) {
    return raw.replace(
      globalRegex,
      `$1[global]\nignoreImports = ["${pattern}"]\n`,
    );
  }
  // No [global] block — append one.
  const prefix = raw.length === 0 || raw.endsWith('\n') ? '' : '\n';
  return `${raw}${prefix}\n[global]\nignoreImports = ["${pattern}"]\n`;
}

function errMsg(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause);
}
