/**
 * `localcode completion bash` — generate a bash completion script.
 *
 * The script handles top-level flags, subcommands (`plugin`, `daemon`,
 * `update`, `doctor`, `completion`), subcommand arguments, profile
 * names, and reads model names live from `~/.localcode/config.toml`.
 *
 * Install:
 *   localcode completion bash > /etc/bash_completion.d/localcode
 *   # or, user-scoped:
 *   localcode completion bash > ~/.local/share/bash-completion/completions/localcode
 *   source ~/.local/share/bash-completion/completions/localcode
 */

export interface BashCompletionOptions {
  /** Profile names — kept here so a future profile addition only edits one file. */
  readonly profiles: readonly string[];
}

export function generateBashCompletion(
  opts: BashCompletionOptions = { profiles: [] },
): string {
  const profiles = opts.profiles.length > 0
    ? opts.profiles.join(' ')
    : 'default acceptEdits plan dontAsk bypassPermissions';
  return `# bash completion for localcode
# Generated by \`localcode completion bash\`.
#
# Source this file from your bashrc, or drop it into
#   /etc/bash_completion.d/localcode
#   ~/.local/share/bash-completion/completions/localcode

_localcode() {
  local cur prev words cword
  if declare -F _init_completion >/dev/null 2>&1; then
    _init_completion || return
  else
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
  fi

  local top_flags='--profile --dangerously-allow-all --resume --model --web --web-host --web-port --no-open --reconfigure --no-refresh-models --help -h --version -v'
  local subcommands='plugin daemon update doctor completion'
  local profiles='${profiles}'
  local plugin_actions='install uninstall list enable disable'
  local update_actions='check apply download status enable disable'
  local shells='bash zsh fish'

  # Read available models from the user's config (best-effort).
  _localcode_models() {
    local cfg="\${HOME}/.localcode/config.toml"
    [ -r "$cfg" ] || return 0
    awk '
      /^\\[model\\]/ { in_model = 1; next }
      /^\\[/ { in_model = 0 }
      in_model && /^available *= *\\[/ {
        line = $0
        sub(/^[^\\[]*\\[/, "", line)
        sub(/\\].*/, "", line)
        gsub(/[",]/, " ", line)
        print line
      }
    ' "$cfg" 2>/dev/null
  }

  case "$prev" in
    --profile)
      COMPREPLY=( $(compgen -W "$profiles" -- "$cur") )
      return 0 ;;
    --model)
      COMPREPLY=( $(compgen -W "$(_localcode_models)" -- "$cur") )
      return 0 ;;
    --resume|--web-host|--web-port|--project-root)
      return 0 ;;
  esac

  # Subcommand dispatch.
  local cmd=""
  local i
  for (( i=1; i < COMP_CWORD; i++ )); do
    case "\${COMP_WORDS[$i]}" in
      plugin|daemon|update|doctor|completion)
        cmd="\${COMP_WORDS[$i]}"
        break ;;
    esac
  done

  case "$cmd" in
    plugin)
      if [ "$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "$plugin_actions --help" -- "$cur") )
      fi
      return 0 ;;
    update)
      if [ "$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "$update_actions --help" -- "$cur") )
      fi
      return 0 ;;
    doctor)
      COMPREPLY=( $(compgen -W "--json --help" -- "$cur") )
      return 0 ;;
    completion)
      if [ "$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "$shells" -- "$cur") )
      fi
      return 0 ;;
    daemon)
      COMPREPLY=( $(compgen -W "--help" -- "$cur") )
      return 0 ;;
  esac

  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$top_flags" -- "$cur") )
    return 0
  fi
  # Default — subcommand or project root path.
  COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") $(compgen -d -- "$cur") )
  return 0
}

complete -F _localcode localcode
`;
}
