/**
 * `localcode completion fish` — generate a fish completion script.
 *
 * Install:
 *   localcode completion fish > ~/.config/fish/completions/localcode.fish
 */

export interface FishCompletionOptions {
  readonly profiles: readonly string[];
}

export function generateFishCompletion(
  opts: FishCompletionOptions = { profiles: [] },
): string {
  const profiles = opts.profiles.length > 0
    ? opts.profiles.join(' ')
    : 'default acceptEdits plan dontAsk bypassPermissions';
  return `# fish completion for localcode
# Generated by \`localcode completion fish\`.

function __localcode_models
  set -l cfg "$HOME/.localcode/config.toml"
  test -r "$cfg"; or return 0
  awk '
    /^\\[model\\]/ { in_model = 1; next }
    /^\\[/ { in_model = 0 }
    in_model && /^available *= *\\[/ {
      line = $0
      sub(/^[^\\[]*\\[/, "", line)
      sub(/\\].*/, "", line)
      gsub(/[",]/, " ", line)
      print line
    }
  ' "$cfg" 2>/dev/null
end

function __localcode_uses_subcommand
  set -l cmd (commandline -opc)
  set -e cmd[1]
  for token in $cmd
    switch $token
      case plugin daemon update doctor completion
        echo $token
        return 0
    end
  end
  return 1
end

function __localcode_needs_subcommand
  not __localcode_uses_subcommand >/dev/null
end

function __localcode_at_subcommand_arg
  set -l sub (__localcode_uses_subcommand)
  test -z "$sub"; and return 1
  set -l cmd (commandline -opc)
  set -l count (count $cmd)
  # cmd = [localcode, ..., <sub>, <arg?>]; argument index relative to <sub>
  set -l sub_idx 0
  for i in (seq (count $cmd))
    if test "$cmd[$i]" = "$sub"
      set sub_idx $i
      break
    end
  end
  set -l offset (math $count - $sub_idx)
  test "$offset" -eq 1; and echo "$sub"; and return 0
  return 1
end

# Top-level subcommand list (only when no subcommand has been chosen).
complete -f -c localcode -n '__localcode_needs_subcommand' -a 'plugin' -d 'Manage plugins'
complete -f -c localcode -n '__localcode_needs_subcommand' -a 'daemon' -d 'Run persistent cron daemon'
complete -f -c localcode -n '__localcode_needs_subcommand' -a 'update' -d 'Auto-update sub-CLI'
complete -f -c localcode -n '__localcode_needs_subcommand' -a 'doctor' -d 'Diagnose installation health'
complete -f -c localcode -n '__localcode_needs_subcommand' -a 'completion' -d 'Print shell completion script'

# Top-level flags.
complete -c localcode -l profile -x -a '${profiles}' -d 'Permission profile'
complete -c localcode -l dangerously-allow-all -d 'Deprecated. Equivalent to --profile dontAsk'
complete -c localcode -l resume -x -d 'Resume a session by id'
complete -c localcode -l model -x -a '(__localcode_models)' -d 'Override active model'
complete -c localcode -l web -d 'Launch the browser UI'
complete -c localcode -l web-host -x -d 'Bind host for --web'
complete -c localcode -l web-port -x -d 'First port for --web'
complete -c localcode -l no-open -d 'Do not auto-open the browser'
complete -c localcode -l reconfigure -d 'Re-run onboarding'
complete -c localcode -l no-refresh-models -d 'Skip startup model refresh'
complete -c localcode -l help -s h -d 'Show help'
complete -c localcode -l version -s v -d 'Print version'

# Subcommand arguments.
complete -f -c localcode -n '__localcode_at_subcommand_arg | string match -q plugin' -a 'install uninstall list enable disable' -d 'plugin action'
complete -f -c localcode -n '__localcode_at_subcommand_arg | string match -q update' -a 'check apply download status enable disable' -d 'update action'
complete -f -c localcode -n '__localcode_at_subcommand_arg | string match -q completion' -a 'bash zsh fish' -d 'shell'

# Doctor flags.
complete -c localcode -n '__localcode_uses_subcommand | string match -q doctor' -l json -d 'Emit JSON'
complete -c localcode -n '__localcode_uses_subcommand | string match -q doctor' -l help -d 'Show help'
`;
}
