/**
 * `localcode completion zsh` — generate a zsh completion script.
 *
 * Install:
 *   localcode completion zsh > "$\{fpath[1]\}/_localcode"
 *   autoload -U compinit && compinit
 */

export interface ZshCompletionOptions {
  readonly profiles: readonly string[];
}

export function generateZshCompletion(
  opts: ZshCompletionOptions = { profiles: [] },
): string {
  const profiles = opts.profiles.length > 0
    ? opts.profiles.join(' ')
    : 'default acceptEdits plan dontAsk bypassPermissions';
  return `#compdef localcode
# zsh completion for localcode
# Generated by \`localcode completion zsh\`.

_localcode_models() {
  local cfg="\${HOME}/.localcode/config.toml"
  [[ -r "$cfg" ]] || return 0
  awk '
    /^\\[model\\]/ { in_model = 1; next }
    /^\\[/ { in_model = 0 }
    in_model && /^available *= *\\[/ {
      line = $0
      sub(/^[^\\[]*\\[/, "", line)
      sub(/\\].*/, "", line)
      gsub(/[",]/, " ", line)
      print line
    }
  ' "$cfg" 2>/dev/null
}

_localcode() {
  local -a subcommands top_flags profiles plugin_actions update_actions shells
  subcommands=(
    'plugin:Manage plugins (install/uninstall/list/enable/disable)'
    'daemon:Run the persistent cron daemon'
    'update:Auto-update sub-CLI'
    'doctor:Diagnose installation health'
    'completion:Print shell completion script'
  )
  top_flags=(
    '--profile[Permission profile]:profile:(${profiles})'
    '--dangerously-allow-all[Deprecated. Equivalent to --profile dontAsk]'
    '--resume[Resume a session by id]:session id:'
    '--model[Override active model]:model name:->models'
    '--web[Launch the browser UI]'
    '--web-host[Bind host for --web]:host:'
    '--web-port[First port for --web]:port:'
    '--no-open[Do not auto-open the browser]'
    '--reconfigure[Re-run onboarding]'
    '--no-refresh-models[Skip startup model refresh]'
    '--help[Show help]'
    '-h[Show help]'
    '--version[Print version]'
    '-v[Print version]'
  )
  plugin_actions=(install uninstall list enable disable)
  update_actions=(check apply download status enable disable)
  shells=(bash zsh fish)

  local context state state_descr line
  typeset -A opt_args
  _arguments -C \\
    "\${top_flags[@]}" \\
    '1: :->command' \\
    '*::arg:->args'

  case "$state" in
    command)
      _describe -t commands 'localcode subcommand' subcommands
      _files -/
      ;;
    args)
      case "$line[1]" in
        plugin)
          _arguments \\
            '1: :->plugin_action' \\
            '*::arg:->plugin_arg'
          if [[ "$state" == plugin_action ]]; then
            _describe -t actions 'plugin action' plugin_actions
          fi
          ;;
        update)
          _arguments \\
            '1: :->update_action'
          if [[ "$state" == update_action ]]; then
            _describe -t actions 'update action' update_actions
          fi
          ;;
        doctor)
          _arguments \\
            '--json[Emit machine-readable JSON]' \\
            '--help[Show help]'
          ;;
        completion)
          _arguments \\
            '1: :->shell'
          if [[ "$state" == shell ]]; then
            _describe -t shells 'shell' shells
          fi
          ;;
        daemon)
          _arguments '--help[Show help]'
          ;;
      esac
      ;;
    models)
      local -a models
      models=($(_localcode_models))
      _describe -t models 'model' models
      ;;
  esac
}

compdef _localcode localcode
`;
}
