#!/usr/bin/env bun
/**
 * embed-web — bundle the Vite SPA build into a TypeScript module.
 *
 * Reads every file in `<repo>/dist-web/`, base64-encodes the bytes, and
 * writes a single `EMBEDDED_ASSETS` map keyed by request path to
 * `src/web/bundle/embedded-assets.ts`. The generated file replaces the
 * stub committed to git so the production `bun build` ships a single
 * binary with the SPA inlined.
 *
 * Run order:
 *   1. `bun run build:web`        → vite build → dist-web/
 *   2. `bun run scripts/embed-web.ts` → src/web/bundle/embedded-assets.ts
 *   3. `bun build src/cli.tsx --outdir dist --target bun`
 *
 * The generated file is gitignored. Re-run after every SPA change.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { join, relative, resolve } from 'node:path';

const ROOT = resolve(import.meta.dir, '..');
const SRC_DIR = join(ROOT, 'dist-web');
const OUT_FILE = join(ROOT, 'src/web/bundle/embedded-assets.ts');

interface Entry {
  mime: string;
  bytes: string;
}

if (!existsSync(SRC_DIR)) {
  process.stderr.write(
    `[embed-web] Missing ${SRC_DIR} — run 'bun run build:web' first.\n`,
  );
  process.exit(1);
}

const ENTRIES: Record<string, Entry> = {};

function walk(dir: string): void {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) {
      walk(full);
      continue;
    }
    const rel = '/' + relative(SRC_DIR, full).replace(/\\/g, '/');
    const buf = readFileSync(full);
    ENTRIES[rel] = { mime: inferMime(rel), bytes: buf.toString('base64') };
  }
}

function inferMime(p: string): string {
  if (p.endsWith('.html')) return 'text/html; charset=utf-8';
  if (p.endsWith('.js') || p.endsWith('.mjs'))
    return 'application/javascript; charset=utf-8';
  if (p.endsWith('.css')) return 'text/css; charset=utf-8';
  if (p.endsWith('.json')) return 'application/json';
  if (p.endsWith('.svg')) return 'image/svg+xml';
  if (p.endsWith('.woff2')) return 'font/woff2';
  if (p.endsWith('.woff')) return 'font/woff';
  if (p.endsWith('.ttf')) return 'font/ttf';
  if (p.endsWith('.png')) return 'image/png';
  if (p.endsWith('.jpg') || p.endsWith('.jpeg')) return 'image/jpeg';
  if (p.endsWith('.webp')) return 'image/webp';
  if (p.endsWith('.ico')) return 'image/x-icon';
  if (p.endsWith('.map')) return 'application/json';
  if (p.endsWith('.txt')) return 'text/plain; charset=utf-8';
  return 'application/octet-stream';
}

walk(SRC_DIR);

if (Object.keys(ENTRIES).length === 0) {
  process.stderr.write(
    `[embed-web] No assets found under ${SRC_DIR}. Did 'bun run build:web' succeed?\n`,
  );
  process.exit(1);
}

if (ENTRIES['/index.html'] === undefined) {
  process.stderr.write(
    `[embed-web] dist-web/index.html missing — refusing to write a bundle without an entry document.\n`,
  );
  process.exit(1);
}

const tsContent = `// AUTO-GENERATED by scripts/embed-web.ts. DO NOT EDIT BY HAND.
// Run 'bun run build:web && bun run embed-web' to regenerate.

export interface EmbeddedAsset {
  readonly mime: string;
  readonly bytes: string;
}

export const EMBEDDED_ASSETS: Readonly<Record<string, EmbeddedAsset>> = ${JSON.stringify(
  ENTRIES,
  null,
  2,
)};

export const EMBEDDED_BUILD_INFO = {
  generatedAt: ${Date.now()},
  isStub: false,
} as const;
`;

mkdirSync(join(ROOT, 'src/web/bundle'), { recursive: true });
writeFileSync(OUT_FILE, tsContent);
process.stdout.write(
  `[embed-web] Embedded ${Object.keys(ENTRIES).length} assets → ${relative(
    ROOT,
    OUT_FILE,
  )}\n`,
);
